version: "3.9"
services:

  mysql:
    image: mysql
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    ports: 
      - "3306:3306"
      
  postgres:
    image: postgres
    container_name: postgresqlDB
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "9000:80"


