database:
  driver: mysql
  host: localhost
  database: customer
  username: root
  password: password
# database:
#   driver: postgres
#   host: localhost
#   database: customer
#   username: username
#   password: password
